### ISSUE TITLE
Rate limited

### ISSUE THREAD

**Issue by ajagnanan1** [serverless/serverless-helpers-js#6]
I sometimes get rate limited, from calling the cloudformation api. Here's the log snippet:

```
\"error\":\"Throttling: Rate exceeded\\n    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/query.js:40:29)\\n    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)\\n    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\\n
```

Not sure what can be done though :cry:

**Comment by HyperBrain** [comment]
I will have a look tomorrow
